export const DEAL_WORD_FORMS = {
  teklif: {
    bare: "teklif",
    pdfLabel: "Teklif PDF",
    acc: "teklifi",
    dat: "teklife",
    plural: "teklifler",
    pluralAcc: "teklifleri",
    gen: "teklifin",
    genPlural: "tekliflerin",
    loc: "teklifte",
    pluralLoc: "tekliflerde",
    ctaLabel: "Teklifi Görüntüle",
    possYours: "Teklifiniz",
    possYoursAcc: "teklifinizi",
  },
  randevu: {
    bare: "randevu",
    pdfLabel: "Randevu Özeti PDF",
    acc: "randevuyu",
    dat: "randevuya",
    plural: "randevular",
    pluralAcc: "randevuları",
    gen: "randevunun",
    genPlural: "randevuların",
    loc: "randevuda",
    pluralLoc: "randevularda",
    ctaLabel: "Randevuyu Görüntüle",
    possYours: "Randevunuz",
    possYoursAcc: "randevunuzu",
  },
  uyelik: {
    bare: "üyelik",
    pdfLabel: "Üyelik Özeti PDF",
    acc: "üyeliği",
    dat: "üyeliğe",
    plural: "üyelikler",
    pluralAcc: "üyelikleri",
    gen: "üyeliğin",
    genPlural: "üyeliklerin",
    loc: "üyelikte",
    pluralLoc: "üyeliklerde",
    ctaLabel: "Üyeliği Görüntüle",
    possYours: "Üyeliğiniz",
    possYoursAcc: "üyeliğinizi",
  },
  rezervasyon: {
    bare: "rezervasyon",
    pdfLabel: "Rezervasyon Özeti PDF",
    acc: "rezervasyonu",
    dat: "rezervasyona",
    plural: "rezervasyonlar",
    pluralAcc: "rezervasyonları",
    gen: "rezervasyonun",
    genPlural: "rezervasyonların",
    loc: "rezervasyonda",
    pluralLoc: "rezervasyonlarda",
    ctaLabel: "Rezervasyonu Görüntüle",
    possYours: "Rezervasyonunuz",
    possYoursAcc: "rezervasyonunuzu",
  },
};

// Müşteri Takibi sekmesindeki liste UI'ı (ekle butonu, arama, boş durumlar,
// tablo başlığı, dışa aktar/düzenle modal başlıkları) için hazır metinler.
export const DEAL_TAB_STRINGS = {
  teklif: {
    navLabel: "Teklifler",
    addLabel: "Teklif ekle",
    searchPlaceholder: "Teklif ara (başlık, müşteri)...",
    openFilterLabel: "Açık teklifler",
    openValueLabel: "Açık teklif değeri",
    openGenPluralPhrase: "Açık tekliflerin",
    emptyDefault: "Henüz teklif eklenmedi.",
    emptySearch: "Aramayla eşleşen teklif yok.",
    columnHeader: "Teklif",
    exportTitle: "Teklifleri Dışa Aktar",
    editTitle: "Teklifi düzenle",
    deleteTitle: "Teklifi sil",
    newTitle: "Yeni teklif",
    exportFilename: "teklifler.xlsx",
  },
  randevu: {
    navLabel: "Randevular",
    addLabel: "Randevu ekle",
    searchPlaceholder: "Randevu ara (başlık, müşteri)...",
    openFilterLabel: "Bekleyen randevular",
    openValueLabel: "Bekleyen randevu değeri",
    openGenPluralPhrase: "Bekleyen randevuların",
    emptyDefault: "Henüz randevu eklenmedi.",
    emptySearch: "Aramayla eşleşen randevu yok.",
    columnHeader: "Randevu",
    exportTitle: "Randevuları Dışa Aktar",
    editTitle: "Randevuyu düzenle",
    deleteTitle: "Randevuyu sil",
    newTitle: "Yeni randevu",
    exportFilename: "randevular.xlsx",
  },
  uyelik: {
    navLabel: "Üyelikler",
    addLabel: "Üyelik ekle",
    searchPlaceholder: "Üyelik ara (başlık, müşteri)...",
    openFilterLabel: "Bekleyen üyelikler",
    openValueLabel: "Bekleyen üyelik değeri",
    openGenPluralPhrase: "Bekleyen üyeliklerin",
    emptyDefault: "Henüz üyelik eklenmedi.",
    emptySearch: "Aramayla eşleşen üyelik yok.",
    columnHeader: "Üyelik",
    exportTitle: "Üyelikleri Dışa Aktar",
    editTitle: "Üyeliği düzenle",
    deleteTitle: "Üyeliği sil",
    newTitle: "Yeni üyelik",
    exportFilename: "uyelikler.xlsx",
  },
  rezervasyon: {
    navLabel: "Rezervasyonlar",
    addLabel: "Rezervasyon ekle",
    searchPlaceholder: "Rezervasyon ara (başlık, müşteri)...",
    openFilterLabel: "Bekleyen rezervasyonlar",
    openValueLabel: "Bekleyen rezervasyon değeri",
    openGenPluralPhrase: "Bekleyen rezervasyonların",
    emptyDefault: "Henüz rezervasyon eklenmedi.",
    emptySearch: "Aramayla eşleşen rezervasyon yok.",
    columnHeader: "Rezervasyon",
    exportTitle: "Rezervasyonları Dışa Aktar",
    editTitle: "Rezervasyonu düzenle",
    deleteTitle: "Rezervasyonu sil",
    newTitle: "Yeni rezervasyon",
    exportFilename: "rezervasyonlar.xlsx",
  },
};

// "Örnek verilerle başla" — şirket bir sektör seçtiyse (şimdilik 3 sektör
// için), örnek kayıtlar o sektörün gerçek diliyle (başlık, özel alan, etiket)
// geliyor. Diğer sektörlerde/sektör seçilmemişse seedDemoData'daki genel
// (sektörden bağımsız) sabit set kullanılmaya devam ediyor.
export const SECTOR_DEMO_PRESETS = {
  guzellik_bakim: {
    customers: [
      { name: "Örnek Müşteri - Elif Kaya", customerType: "bireysel", phone: "0532 000 00 11" },
      { name: "Örnek Müşteri - Zeynep Demir", customerType: "bireysel", phone: "0532 000 00 12" },
    ],
    deals: [
      {
        customerIndex: 0,
        title: "Lazer Epilasyon Paketi",
        value: 3500,
        cost: 0,
        stage: "kazanildi",
        customFields: { hizmet_turu: "Lazer Epilasyon", hizmet_suresi_dk: 45 },
      },
      {
        customerIndex: 1,
        title: "Saç Kesimi Randevusu",
        value: 400,
        cost: 0,
        stage: "kaybedildi",
        tags: ["Gelmedi"],
        customFields: { hizmet_turu: "Saç Kesimi/Boyama" },
      },
      {
        customerIndex: 0,
        title: "Cilt Bakımı Randevusu",
        value: 800,
        cost: 0,
        stage: "muzakere",
        reminderToday: true,
        reminder: "Randevu hatırlatması yap",
        customFields: { hizmet_turu: "Cilt Bakımı" },
      },
    ],
  },
  saglik_klinik: {
    customers: [
      { name: "Örnek Hasta - Mehmet Aydın", customerType: "bireysel", phone: "0532 000 00 21" },
      { name: "Örnek Hasta - Fatma Şahin", customerType: "bireysel", phone: "0532 000 00 22" },
    ],
    deals: [
      {
        customerIndex: 0,
        title: "Diş Muayenesi ve Tedavi",
        value: 2500,
        cost: 0,
        stage: "kazanildi",
        customFields: { tedavi_hizmet: "Diş dolgusu", tetkik_turu: "Panoramik röntgen" },
      },
      {
        customerIndex: 1,
        title: "Check-up Paketi",
        value: 1800,
        cost: 0,
        stage: "teklif",
        reminderToday: true,
        reminder: "Tedavi planını sun",
        customFields: { tedavi_hizmet: "Genel check-up" },
      },
      {
        customerIndex: 0,
        title: "Kontrol Muayenesi",
        value: 300,
        cost: 0,
        stage: "muzakere",
        customFields: { tedavi_hizmet: "Kontrol" },
      },
    ],
  },
  sanayi_esnaf: {
    customers: [
      { name: "Örnek Müşteri - Ahmet Yılmaz", customerType: "bireysel", phone: "0532 000 00 31" },
      { name: "Örnek Müşteri - Kaya Nakliyat", customerType: "kurumsal", phone: "0532 000 00 32" },
    ],
    deals: [
      {
        customerIndex: 0,
        title: "Oto Boya İşlemi",
        value: 8500,
        cost: 3000,
        stage: "kazanildi",
        customFields: {
          servis_turu: "Oto Boya",
          arac_ekipman_bilgisi: "34 ABC 123, Toyota Corolla",
          tahmini_ucret: 8000,
        },
      },
      {
        customerIndex: 1,
        title: "Kaynak İşi Teklifi",
        value: 4200,
        cost: 0,
        stage: "teklif",
        reminderToday: true,
        reminder: "Parça durumunu kontrol et",
        customFields: { servis_turu: "Kaynak İşi", parca_durumu: "Sipariş verildi" },
      },
      {
        customerIndex: 0,
        title: "Elektrik Arızası",
        value: 1200,
        cost: 0,
        stage: "ilk_gorusme",
        customFields: { servis_turu: "Elektrik İşi" },
      },
    ],
  },
  emlak: {
    customers: [
      { name: "Örnek Müşteri - Can Öztürk", customerType: "bireysel", phone: "0532 000 00 41" },
      { name: "Örnek Müşteri - Ada Yapı A.Ş.", customerType: "kurumsal", phone: "0532 000 00 42" },
    ],
    deals: [
      {
        customerIndex: 0,
        title: "3+1 Daire Satışı - Kadıköy",
        value: 2500000,
        cost: 0,
        stage: "kazanildi",
        customFields: {
          mulk_tipi: "Daire",
          islem_turu: "Satış",
          metrekare: 120,
          ilan_no: "KDK-1042",
        },
      },
      {
        customerIndex: 1,
        title: "Ofis Kiralama Teklifi",
        value: 45000,
        cost: 0,
        stage: "teklif",
        reminderToday: true,
        reminder: "Mülk fotoğraflarını gönder",
        customFields: { mulk_tipi: "İşyeri", islem_turu: "Kiralama", metrekare: 200 },
      },
      {
        customerIndex: 0,
        title: "Villa Görüşmesi",
        value: 4500000,
        cost: 0,
        stage: "ilk_gorusme",
        customFields: { mulk_tipi: "Villa", islem_turu: "Satış" },
      },
    ],
  },
  dijital_ajans: {
    customers: [
      { name: "Örnek Müşteri - Lezzet Cafe", customerType: "kurumsal", phone: "0532 000 00 51" },
      {
        name: "Örnek Müşteri - Parlak Kozmetik",
        customerType: "kurumsal",
        phone: "0532 000 00 52",
      },
    ],
    deals: [
      {
        customerIndex: 0,
        title: "Sosyal Medya Yönetimi (Aylık)",
        value: 12000,
        cost: 0,
        stage: "kazanildi",
        customFields: {
          hizmet_turu: "Sosyal medya yönetimi",
          sozlesme_suresi: "Aylık",
          aylik_butce: 5000,
        },
      },
      {
        customerIndex: 1,
        title: "Web Sitesi Yenileme Teklifi",
        value: 35000,
        cost: 0,
        stage: "teklif",
        reminderToday: true,
        reminder: "Teklifi takip et",
        customFields: { hizmet_turu: "Web tasarım", sozlesme_suresi: "Tek seferlik" },
      },
      {
        customerIndex: 0,
        title: "SEO Danışmanlığı Görüşmesi",
        value: 8000,
        cost: 0,
        stage: "ilk_gorusme",
        customFields: { hizmet_turu: "SEO" },
      },
    ],
  },
  uretim_satis: {
    customers: [
      {
        name: "Örnek Müşteri - Yıldız Market Zinciri",
        customerType: "kurumsal",
        phone: "0532 000 00 61",
      },
      {
        name: "Örnek Müşteri - Deniz Toptan Gıda",
        customerType: "kurumsal",
        phone: "0532 000 00 62",
      },
    ],
    deals: [
      {
        customerIndex: 0,
        title: "Aylık Ürün Sevkiyatı",
        value: 85000,
        cost: 0,
        stage: "kazanildi",
        customFields: {
          urun_grubu: "Gıda ambalaj",
          siparis_miktari: 5000,
          sevkiyat_durumu: "Teslim edildi",
        },
      },
      {
        customerIndex: 1,
        title: "Toptan Sipariş Teklifi",
        value: 42000,
        cost: 0,
        stage: "teklif",
        reminderToday: true,
        reminder: "Fiyat teklifini takip et",
        customFields: { urun_grubu: "Temizlik ürünleri", siparis_miktari: 2000 },
      },
      {
        customerIndex: 0,
        title: "Yeni Ürün Görüşmesi",
        value: 15000,
        cost: 0,
        stage: "ilk_gorusme",
        customFields: { urun_grubu: "Kağıt ürünleri" },
      },
    ],
  },
  hizmet_danismanlik: {
    customers: [
      { name: "Örnek Müşteri - Vizyon Holding", customerType: "kurumsal", phone: "0532 000 00 71" },
      { name: "Örnek Müşteri - Selin Aydın", customerType: "bireysel", phone: "0532 000 00 72" },
    ],
    deals: [
      {
        customerIndex: 0,
        title: "Kurumsal Verimlilik Danışmanlığı",
        value: 60000,
        cost: 0,
        stage: "kazanildi",
        customFields: { ucretlendirme_modeli: "Proje bazlı", proje_kapsami: "Süreç iyileştirme" },
      },
      {
        customerIndex: 1,
        title: "Kariyer Koçluğu Teklifi",
        value: 6000,
        cost: 0,
        stage: "teklif",
        reminderToday: true,
        reminder: "Teklifi takip et",
        customFields: { ucretlendirme_modeli: "Aylık paket" },
      },
      {
        customerIndex: 0,
        title: "Yeni Proje Görüşmesi",
        value: 25000,
        cost: 0,
        stage: "muzakere",
        customFields: { ucretlendirme_modeli: "Saatlik" },
      },
    ],
  },
  perakende: {
    customers: [
      { name: "Örnek Müşteri - Burak Kaya", customerType: "bireysel", phone: "0532 000 00 81" },
      { name: "Örnek Müşteri - Naz Yılmaz", customerType: "bireysel", phone: "0532 000 00 82" },
    ],
    deals: [
      {
        customerIndex: 0,
        title: "Mağaza İçi Alışveriş",
        value: 3200,
        cost: 0,
        stage: "kazanildi",
        customFields: { satis_kanali: "Mağaza", urun_kategorisi: "Giyim" },
      },
      {
        customerIndex: 1,
        title: "Online Sipariş Teklifi",
        value: 1500,
        cost: 0,
        stage: "teklif",
        reminderToday: true,
        reminder: "Siparişi takip et",
        customFields: { satis_kanali: "Online", urun_kategorisi: "Ayakkabı" },
      },
      {
        customerIndex: 0,
        title: "Telefon Siparişi Görüşmesi",
        value: 900,
        cost: 0,
        stage: "ilk_gorusme",
        customFields: { satis_kanali: "Telefon" },
      },
    ],
  },
  spor_merkezi: {
    customers: [
      { name: "Örnek Üye - Deniz Arslan", customerType: "bireysel", phone: "0532 000 00 91" },
      { name: "Örnek Üye - Ege Korkmaz", customerType: "bireysel", phone: "0532 000 00 92" },
    ],
    deals: [
      {
        customerIndex: 0,
        title: "Yıllık Üyelik",
        value: 18000,
        cost: 0,
        stage: "kazanildi",
        customFields: { uyelik_paketi: "Yıllık" },
      },
      {
        customerIndex: 1,
        title: "PT Paketi Teklifi",
        value: 9000,
        cost: 0,
        stage: "teklif",
        reminderToday: true,
        reminder: "Paketi takip et",
        customFields: { uyelik_paketi: "PT Paketi", antrenor: "Mert Hoca" },
      },
      {
        customerIndex: 0,
        title: "Deneme Dersi Görüşmesi",
        value: 250,
        cost: 0,
        stage: "ilk_gorusme",
        customFields: { uyelik_paketi: "Aylık" },
      },
    ],
  },
  egitim_kurs: {
    customers: [
      { name: "Örnek Öğrenci - Defne Yıldız", customerType: "bireysel", phone: "0532 000 01 01" },
      { name: "Örnek Öğrenci - Kerem Çelik", customerType: "bireysel", phone: "0532 000 01 02" },
    ],
    deals: [
      {
        customerIndex: 0,
        title: "İngilizce Kursu Kaydı",
        value: 7500,
        cost: 0,
        stage: "kazanildi",
        customFields: { kurs_programi: "Yabancı Dil", egitmen: "Ayşe Öğretmen" },
      },
      {
        customerIndex: 1,
        title: "Sürücü Kursu Teklifi",
        value: 12000,
        cost: 0,
        stage: "teklif",
        reminderToday: true,
        reminder: "Kaydı takip et",
        customFields: { kurs_programi: "Sürücü Kursu" },
      },
      {
        customerIndex: 0,
        title: "Deneme Dersi Görüşmesi",
        value: 500,
        cost: 0,
        stage: "ilk_gorusme",
        customFields: { kurs_programi: "Müzik/Sanat" },
      },
    ],
  },
};
